apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fbctest413
  namespace: user1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:e448b0dbd3a4ac55cac6299e639131409b3189984996ecc33bd3b0c522c8f6e2
        name: container-image
        resources: {}
status: {}
